from views.styles import (
    BG_COLOR,
    PRIMARY_COLOR,
    GREY,
    ERROR_COLOR,
    WHITE,
    BG_DARK,
    PRIMARY_BLUE,
    ACCENT_ORANGE,
    TEXT_TITLE,
    TEXT_SUB,
    STYLE_PAGE_CONTAINER,
    campo_estilo,
    BTN_MAIN,
    BTN_SPECIAL,
)

__all__ = [
    'BG_COLOR',
    'PRIMARY_COLOR',
    'GREY',
    'ERROR_COLOR',
    'WHITE',
    'BG_DARK',
    'PRIMARY_BLUE',
    'ACCENT_ORANGE',
    'TEXT_TITLE',
    'TEXT_SUB',
    'STYLE_PAGE_CONTAINER',
    'campo_estilo',
    'BTN_MAIN',
    'BTN_SPECIAL',
    'styles',
]